### ISSUE TITLE
Division in python 3 throws an error

### ISSUE THREAD

**Issue by joearasin** [Calysto/calysto_scheme#2]
Input: `(/ 1.0 2.0)`
Output: 

```
Traceback (most recent call last):
  File "In [45]", line 1, col 1, in '/'
UnhandledException: 'module' object has no attribute 'div'
```

**Comment by joearasin** [comment]
Swapping operator.div for operator.truediv on line 642 fixes this. I'm not sure if this is desired behavior / breaks python 2, though.

**Comment by dsblank** [comment]
Good catch... looking into it.

**Comment by dsblank** [comment]
Fixed in 4d7225a, and it still works in Python 2.7.6. Thanks!

**Comment by joearasin** [comment]
Awesome -- thank you!
